# data:
#     gtf: data/{species}/{source}.gtf
#     cerberus:
#       ends: data/{species}/{source}_{end_type}.bed
#       ics: data/{species}/{source}_ic.tsv
#       agg_ends: data/{species}/{end_type}_agg.bed
#       agg_ics: data/{species}/ic_agg.tsv
#       ref: data/{species}/cerberus_ref.h5
#       annot: data/{species}/cerberus_{source}_annot.h5
#       triplets: data/{species}/cerberus_triplets.h5
#
# ref:
#   human:
#     meta_link: https://github.com/guigolab/gencode-cls-master-table/releases/latest/download/Hv3_metadata.tsv.gz
#   mouse:
#     meta_link: https://github.com/guigolab/gencode-cls-master-table/releases/latest/download/Mv2_metadata.tsv.gz
#   meta_gz: ref/{species}/metadata.tsv.gz
#   meta: ref/{species}/metadata.tsv

ref:
  human:
      annot_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/gencode.v43.annotation.gtf.gz
      fa_link: https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15/@@download/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz
  mouse:
      annot_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.annotation.gtf.gz
      fa_link: https://www.encodeproject.org/files/mm10_no_alt_analysis_set_ENCODE/@@download/mm10_no_alt_analysis_set_ENCODE.fasta.gz
  annot_gz: ref/{species}/annot.gtf.gz
  annot: ref/{species}/annot.gtf
  fa_gz: ref/{species}/ref.fa.gz
  fa: ref/{species}/ref.fa

  ends: ref/{species}/{end_mode}.bed
  ics: ref/{species}/ics.tsv

data:
  meta: data/{species}/metadata.tsv
  gff_gz: data/{species}/{dataset}.gff.gz
  gff: data/{species}/{dataset}.gff
  gtf_no_sirv: data/{species}/{dataset}_no_sirv.gff
  ab: data/{species}/{dataset}_abundance.tsv

  sqanti_gff: data/{species}/{dataset}/{dataset}_sqanti_corrected.gtf.cds.gff

  cerb:
    ends: data/{species}/cerberus/{dataset}/{end_mode}.bed
    ics: data/{species}/cerberus/{dataset}/ics.tsv
    agg_ends: data/{species}/cerberus/agg_ends.bed
    agg_ics: data/{species}/cerberus/agg_ics.tsv

    ca_ref: data/{species}/cerberus/ca_ref.h5

sqanti_path: /dfs8/pub/freese//mortazavi_lab/bin/SQANTI3/
cupcake_path: /dfs8/pub/freese//mortazavi_lab/bin/cDNA_Cupcake/
